spring:
    datasource:
      master:
        hikari:
          username: root
          password: password
          driver-class-name: com.mysql.cj.jdbc.Driver
          jdbc-url: jdbc:mysql://localhost:3307/test2
      slave:
        hikari:
          username: root
          password: password
          driver-class-name: com.mysql.cj.jdbc.Driver
          jdbc-url: jdbc:mysql://localhost:3308/test2
jpa:
  hibernate:
    ddl-auto: create-drop
  properties:
    hibernate:
      format-sql: true
      show_sql: true
  database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.springframework.jdbc.datasource.SimpleDriverDataSource: DEBUG
    org.hibernate.SQL: DEBUG
